%YAML:1.0
---
dataset_name: kitti

kitti:

    dataset_dir: /home/lacie/Github/data/00/image_0
    num_images: 4541

    camera_info.cx: 607.1928
    camera_info.cy: 185.2157
    camera_info.fx: 718.856
    camera_info.fy: 718.856

    is_draw_true_traj: "true"
    true_traj_filename: /home/lacie/Github/data/00/00.txt

# ================================================
# =============== General settings ===============
# ================================================
max_num_imgs_to_proc: 4541
is_pcl_wait_for_keypress: "false"
cv_waitkey_time: 1
save_predicted_traj_to: /home/lacie/Github/data/00/cam_traj.txt
output_folder: output

# ------------------- Feature Matching -------------------
# ORB settings
number_of_keypoints_to_extract: 1500
max_number_of_keypoints: 1500
scale_factor: 1.2
level_pyramid: 4
score_threshold: 20

feature_match_method_index_initialization: 1
feature_match_method_index_pnp: 1
feature_match_method_index_triangulation: 1

# Matching descriptos
feature_match_method_index: 3
  # method 1: the method in Dr. Xiang Gao's slambook:
  #           distance_threshold = max<float>(min_dis * match_ratio, 30.0);
  # method 2: the method in Lowe's 2004 paper:
  #           min dis / second min dis < 0.8
  # method 3: match a point with its neighboring points and then apply Dr. Xiang Gao's criteria.
xiang_gao_method_match_ratio: 2
lowe_method_dist_ratio: 0.8
method_3_feature_dist_threshold: 50.0

# Method 3 parameters:
max_matching_pixel_dist_in_pnp: 50
max_matching_pixel_dist_in_initialization: 100
max_matching_pixel_dist_in_triangulation: 100

# remove wrong matches
kpts_uniform_selection_grid_size: 16
kpts_uniform_selection_max_pts_per_grid: 8

# ------------------- RANSAC Essential matrix -------------------
findEssentialMat_prob: 0.999
findEssentialMat_threshold: 1.0



# ------------------- Triangulation -------------------
min_triang_angle: 1.0
max_ratio_between_max_angle_and_median_angle: 20

# ------------------- Initialization -------------------
min_inlier_matches: 15
min_pixel_dist: 50
min_median_triangulation_angle: 1.0
assumed_mean_pts_depth_during_vo_init: 0.8

# ------------------- Tracking -------------------
min_dist_between_two_keyframes: 0.03
max_possible_dist_to_prev_keyframe: 0.3

# ------------------- Optimization -------------------
is_enable_ba: "true"
num_prev_frames_to_opti_by_ba: 5
information_matrix: "1.0 0.0 0.0 1.0"
is_ba_fix_map_points: "true"




















