%YAML:1.0
---
Camera.RGB: 1
Camera.bFishEye: 0
Camera.bf: 386.1448
Camera.cx: 607.1928
Camera.cy: 185.2157
Camera.fps: 10.0
Camera.fx: 718.856
Camera.fy: 718.856
Camera.height: 376
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.type: PinHole
Camera.width: 1241
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7
ORBextractor.nFeatures: 2000
ORBextractor.nLevels: 8
ORBextractor.scaleFactor: 1.2
ThDepth: 35.0
Viewer.CameraLineWidth: 3
Viewer.CameraSize: 0.7
Viewer.GraphLineWidth: 1
Viewer.KeyFrameLineWidth: 2
Viewer.KeyFrameSize: 0.6
Viewer.PointSize: 2
Viewer.ViewpointF: 2000
Viewer.ViewpointX: 0
Viewer.ViewpointY: -100
Viewer.ViewpointZ: -0.1